#!/bin/bash

OUTPUT_DIR="/var/www/html/reports"
mkdir -p "$OUTPUT_DIR"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

echo "=== Service Status Check ===" > "$OUTPUT_DIR/service-status.txt"
echo "Timestamp: $TIMESTAMP" >> "$OUTPUT_DIR/service-status.txt"
echo "" >> "$OUTPUT_DIR/service-status.txt"

if service nginx status > /dev/null 2>&1; then
    echo "✓ Nginx: RUNNING" >> "$OUTPUT_DIR/service-status.txt"
else
    echo "✗ Nginx: STOPPED" >> "$OUTPUT_DIR/service-status.txt"
fi

if service ssh status > /dev/null 2>&1; then
    echo "✓ SSH: RUNNING" >> "$OUTPUT_DIR/service-status.txt"
else
    echo "✗ SSH: STOPPED" >> "$OUTPUT_DIR/service-status.txt"
fi

echo "" >> "$OUTPUT_DIR/service-status.txt"
echo "Generated by monitoring system" >> "$OUTPUT_DIR/service-status.txt"

echo "Service check completed at $TIMESTAMP"
