#!/bin/bash

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
OUTPUT_DIR="/var/www/html/reports"

mkdir -p "$OUTPUT_DIR"

CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}')
MEM_USAGE=$(free | grep Mem | awk '{printf("%.2f", ($3/$2) * 100)}')
DISK_USAGE=$(df -h / | tail -1 | awk '{print $5}')
LOAD_AVG=$(uptime | awk '{print $(NF-2), $(NF-1), $NF}')

cat > "$OUTPUT_DIR/latest-metrics.txt" << EOF
=== System Metrics ===
Timestamp: $TIMESTAMP

CPU Usage: $CPU_USAGE%
Memory Usage: $MEM_USAGE%
Disk Usage: $DISK_USAGE
Load Average: $LOAD_AVG

Generated by monitoring system
EOF

echo "Metrics collected at $TIMESTAMP"
