#!/bin/bash

OUTPUT_DIR="/var/www/html/reports"
mkdir -p "$OUTPUT_DIR"

# ===== DAILY REPORT =====
REPORT_DATE=$(date '+%Y-%m-%d')
REPORT_FILE="$OUTPUT_DIR/daily-$REPORT_DATE.txt"

cat > "$REPORT_FILE" << EOF
=== Daily Monitoring Report ===
Date: $REPORT_DATE
Generated: $(date '+%Y-%m-%d %H:%M:%S')

--- System Status ---
$(cat $OUTPUT_DIR/service-status.txt 2>/dev/null || echo "No service data available")

--- Latest Metrics ---
$(cat $OUTPUT_DIR/latest-metrics.txt 2>/dev/null || echo "No metrics data available")

--- Health Checks ---
$(cat $OUTPUT_DIR/health-checks.txt 2>/dev/null || echo "No health check data available")

--- All Systems Report ---
Generated by Project 9 Monitoring System
EOF

echo "Daily report generated: $REPORT_FILE"

# ===== WEEKLY REPORT =====
WEEK_NUMBER=$(date '+%V')
YEAR=$(date '+%Y')
WEEK_REPORT_FILE="$OUTPUT_DIR/weekly-${YEAR}-W${WEEK_NUMBER}.txt"

# Get all daily reports from this week
DAILY_REPORTS=$(find $OUTPUT_DIR -name "daily-*.txt" -mtime -7 | sort -r | head -7)

# Count metrics from the week
TOTAL_METRICS=$(cat $OUTPUT_DIR/latest-metrics.txt 2>/dev/null | grep -c "CPU" || echo "0")
TOTAL_HEALTH_CHECKS=$(find $OUTPUT_DIR -name "daily-*.txt" -mtime -7 | wc -l)

cat > "$WEEK_REPORT_FILE" << EOF
=== Weekly Monitoring Report ===
Week: ${YEAR}-W${WEEK_NUMBER}
Generated: $(date '+%Y-%m-%d %H:%M:%S')
Date Range: Last 7 days

--- Weekly Summary ---
Report Period: $(date -d '7 days ago' '+%Y-%m-%d') to $(date '+%Y-%m-%d')
Total Daily Reports Collected: $TOTAL_HEALTH_CHECKS
Last Updated: $(date '+%Y-%m-%d %H:%M:%S')

--- Current System Status ---
$(cat $OUTPUT_DIR/service-status.txt 2>/dev/null || echo "No service data available")

--- Current Metrics ---
$(cat $OUTPUT_DIR/latest-metrics.txt 2>/dev/null || echo "No metrics data available")

--- Current Health Checks ---
$(cat $OUTPUT_DIR/health-checks.txt 2>/dev/null || echo "No health check data available")

--- Weekly Statistics ---
Monitoring Period: 7 days
Data Points Collected: Multiple
Last Report Generated: $(date '+%Y-%m-%d %H:%M:%S')

--- Recent Daily Reports Available ---
EOF

# Add last 7 daily reports
find $OUTPUT_DIR -name "daily-*.txt" -mtime -7 | sort -r | head -7 | while read report; do
    echo "- $(basename $report)" >> "$WEEK_REPORT_FILE"
done

cat >> "$WEEK_REPORT_FILE" << EOF

--- End of Weekly Report ---
Generated by Project 9 Monitoring System
EOF

echo "Weekly report generated: $WEEK_REPORT_FILE"

# ===== SUMMARY =====
echo ""
echo "=== Report Generation Summary ==="
echo "Daily Report: $REPORT_FILE"
echo "Weekly Report: $WEEK_REPORT_FILE"
echo "Total reports available:"
ls -1 $OUTPUT_DIR/daily-*.txt 2>/dev/null | wc -l
echo "daily reports"
ls -1 $OUTPUT_DIR/weekly-*.txt 2>/dev/null | wc -l
echo "weekly reports"
