#!/bin/bash

OUTPUT_DIR="/var/www/html/reports"
mkdir -p "$OUTPUT_DIR"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

APP_SERVERS=("10.0.10.25" "10.0.11.105")

echo "=== HTTP Health Checks ===" > "$OUTPUT_DIR/health-checks.txt"
echo "Timestamp: $TIMESTAMP" >> "$OUTPUT_DIR/health-checks.txt"
echo "" >> "$OUTPUT_DIR/health-checks.txt"

for server in "${APP_SERVERS[@]}"; do
    echo "Checking $server..." >> "$OUTPUT_DIR/health-checks.txt"
    
    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -m 5 http://$server/health)
    
    if [ "$RESPONSE" == "200" ]; then
        echo "  ✓ Status: UP (HTTP $RESPONSE)" >> "$OUTPUT_DIR/health-checks.txt"
    else
        echo "  ✗ Status: DOWN (HTTP $RESPONSE)" >> "$OUTPUT_DIR/health-checks.txt"
    fi
done

echo "" >> "$OUTPUT_DIR/health-checks.txt"
echo "Generated by monitoring system" >> "$OUTPUT_DIR/health-checks.txt"

echo "Health checks completed at $TIMESTAMP"
